export const Auth = {
	LOGIN_SUCCESS: 'LOGIN_SUCCESS',
	LOGIN_FAIL: 'LOGIN_FAIL',
	SIGNOUT_SUCCESS: 'SIGNOUT_SUCCESS',
	SIGNOUT_FAIL: 'SIGNOUT_FAIL',
	INITIALIZED_AUTH_DATA: 'INITIALIZED_AUTH_DATA',
	RECEIVE_AUTH_DATA: 'RECEIVE_AUTH_DATA',
	REQUEST_AUTH_DATA: 'REQUEST_AUTH_DATA',
	SIGNUP_SUCCESS: 'SIGNUP_SUCCESS',
	SIGNUP_FAIL: 'SIGNUP_FAIL',
}
