export const Auth = {
	LOGIN_SUCCESS: 'LOGIN_SUCCESS',
	LOGIN_FAIL: 'LOGIN_FAIL',
	SIGNOUT_SUCCESS: 'SIGNOUT_SUCCESS',
	SIGNOUT_FAIL: 'SIGNOUT_FAIL',
	INITIALIZED_AUTH_DATA: 'INITIALIZED_AUTH_DATA',
	RECEIVE_AUTH_DATA: 'RECEIVE_AUTH_DATA',
	REQUEST_AUTH_DATA: 'REQUEST_AUTH_DATA',
	SIGNUP_SUCCESS: 'SIGNUP_SUCCESS',
	SIGNUP_FAIL: 'SIGNUP_FAIL',
}

export const Notes = {
	REQUEST_NOTES_DATA: 'REQUEST_NOTES_DATA',
	RECEIVE_NOTES_DATA: 'RECEIVE_NOTES_DATA',
	INITIALIZED_NOTES_DATA: 'INITIALINED_NOTES_DATA',
	ADD_A_NOTE: 'ADD_A_NOTE',
	RESET_NOTES_DATA: 'RESET_NOTES_DATA',
}
