export const Todos = {
	ADD_TODO: 'ADD_TODO',
	UPDATE_TODO: 'UPDATE_TODO',
	REMOVE_TODO: 'REMOVE_TODO',
	RECEIVE_TODOS_DATA: 'RECEIVE_TODOS_DATA',
	CLEAR_COMPELETED_TODOS: 'CLEAR_COMPELETED_TODOS',
	INITIALIZED_TODOS: 'INITIALIZED_TODOS',
}
