export const Auth = {
	LOGIN_SUCCESS: 'LOGIN_SUCCESS',
	LOGIN_FAIL: 'LOGIN_FAIL',
	SIGNOUT: 'SIGNOUT',
	INITIALIZED_AUTH_DATA: 'INITIALIZED_AUTH_DATA',
	RECEIVE_AUTH_DATA: 'RECEIVE_AUTH_DATA',
	REQUEST_AUTH_DATA: 'REQUEST_AUTH_DATA',
}
